# -*- coding: utf-8 -*-
"""FINAL_PLDP_data_analysis_sunflower_oil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsGeLJ-jVMuZSMwQwVOkf661yFmizvB_
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.optimize import curve_fit

# ----------------------------------
# Sphere properties and other constants
# ----------------------------------

d = 0.03          # m
dd = 0.001        # m

r = d/2

m = 0.0157        # kg

rho_oil = 920     # kg/m^3

g = 9.81  # m/s^2

R = 8.314  # J/(mol K)

T_tf = 230 # K

# sphere density
V = (4/3)*np.pi*r**3
rho_s = m/V

print(f"Sphere density = {rho_s:.1f} kg/m^3")


# ----------------------------------
# Read Tracker file
# ----------------------------------

def read_tracker(filename):

    df = pd.read_csv(
        filename,
        skiprows=1
    )

    return df


# ----------------------------------
# Terminal velocity estimate
# ----------------------------------

def terminal_velocity(df, n_points=10):

    vy = pd.to_numeric(
        df["vy"],
        errors="coerce"
    )

    vy = vy.dropna()

    # looks for 10 most negative values, takes the mean and std
    lowest = np.sort(vy)[:n_points]

    v_term = abs(np.mean(lowest))
    v_std = np.std(lowest, ddof=1)

    return v_term, v_std


# ----------------------------------
# Stokes viscosity
# ----------------------------------

def viscosity(v):

    return (
        2*r**2*(rho_s-rho_oil)*g
        /
        (9*v)
    )


# ----------------------------------
# Process one file
# ----------------------------------

def analyze_file(filename):

    df = read_tracker(filename)

    v, dv = terminal_velocity(df)

    eta = viscosity(v)

    deta = eta * dv / v

    return v, dv, eta, deta

# ----------------------------------
# Fitting functinos
# ----------------------------------

def arrhenius_viscosity(T, A, Ea):
    return A * np.exp(Ea / (R * T))


def simple_decay(T, A_0, t_0):
  return A_0*np.exp(-T/t_0)

def VFT(T, eta_0, B):
    return eta_0*np.exp(B/(T+273.15-T_tf))

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_21,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_second_21,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_third_21,9.txt"
]

trial_viscosities = [] # This contains all trials of one temp
trial_velocity = []
viscosity_list = [] # This will contain all final viscosities
error_list = [] # This will contain all final errors of viscosity
vel_list = []
vel_err_list = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    print("\n", file)

    print("v =", round(v,3), "m/s")

    print("viscosity =", round(eta,3), "Pa·s")

    print("error =", round(deta,3), "Pa·s")

    trial_viscosities.append(eta)
    trial_velocity.append(v)

final_viscosity_22 = np.mean(trial_viscosities)
error_viscosity_22 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_22)
error_list.append(error_viscosity_22)
final_velocity_22 = np.mean(trial_velocity)
error_velocity_22 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_22)
vel_err_list.append(error_velocity_22)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/27/m_oil_26,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/27/m_oil_27,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/27/m_oil_27,2.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_27 = np.mean(trial_viscosities)
error_viscosity_27 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_27)
error_list.append(error_viscosity_27)
final_velocity_27 = np.mean(trial_velocity)
error_velocity_27 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_27)
vel_err_list.append(error_velocity_27)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,7.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_32 = np.mean(trial_viscosities)
error_viscosity_32 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_32)
error_list.append(error_viscosity_32)
final_velocity_32 = np.mean(trial_velocity)
error_velocity_32 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_32)
vel_err_list.append(error_velocity_32)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_36,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_36,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_37,7.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_37 = np.mean(trial_viscosities)
error_viscosity_37 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_37)
error_list.append(error_viscosity_37)
final_velocity_37 = np.mean(trial_velocity)
error_velocity_37 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_37)
vel_err_list.append(error_velocity_37)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_41,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_42,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_42,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_second_42,3.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_42 = np.mean(trial_viscosities)
error_viscosity_42 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_42)
error_list.append(error_viscosity_42)
final_velocity_42 = np.mean(trial_velocity)
error_velocity_42 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_42)
vel_err_list.append(error_velocity_42)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_46,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,8.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_47 = np.mean(trial_viscosities)
error_viscosity_47 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_47)
error_list.append(error_viscosity_47)
final_velocity_47 = np.mean(trial_velocity)
error_velocity_47 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_47)
vel_err_list.append(error_velocity_47)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_second_52,4.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_52 = np.mean(trial_viscosities)
error_viscosity_52 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_52)
error_list.append(error_viscosity_52)
final_velocity_52 = np.mean(trial_velocity)
error_velocity_52 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_52)
vel_err_list.append(error_velocity_52)

# DATA 57 DEGREES LEFT OUT DUE TO LARGE ERROR IN RECORDING

# files = [
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_57,2.txt",
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_57,6.txt",
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_second_57,6.txt"
# ]

# trial_viscosities = []

# for file in files:

#     v, dv, eta, deta = analyze_file(file)

#     trial_viscosities.append(eta)

# final_viscosity_57 = np.mean(trial_viscosities)
# error_viscosity_57 = np.std(trial_viscosities, ddof = 1)

# print(trial_viscosities)

# viscosity_list.append(final_viscosity_57)
# error_list.append(error_viscosity_57)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_61,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_second_62,0.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_62 = np.mean(trial_viscosities)
error_viscosity_62 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_62)
error_list.append(error_viscosity_62)
final_velocity_62 = np.mean(trial_velocity)
error_velocity_62 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_62)
vel_err_list.append(error_velocity_62)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/(Order) 66/m_oil_66,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/(Order) 66/m_oil_66,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/(Order) 66/m_oil_66,7.txt"
]

trial_viscosities = []
trial_velocity = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_66 = np.mean(trial_viscosities)
error_viscosity_66 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_66)
error_list.append(error_viscosity_66)
final_velocity_66 = np.mean(trial_velocity)
error_velocity_66 = np.std(trial_velocity, ddof = 1)
vel_list.append(final_velocity_66)
vel_err_list.append(error_velocity_66)

temperatures = [21.9, 26.9333333, 32.33333333, 37.133333, 42.1, 47.225, 52.275, 62.1, 66.4] # degrees Celsius
temp_error = [0.1, 0.305505, 0.351188, 0.493288, 0.244949, 0.403113, 0.189297, 0.2, 0.2645751311]

T = np.array(temperatures)
T_K = T + 273.15 # Conversion to Kelvin for curve_fit()
T_fit = np.linspace(min(T_K), max(T_K), 200)

visc_array = np.array(viscosity_list) # For table with final data
error_array = np.array(error_list) # For table with final data
print(f"Viscosity values: {visc_array}")
print(f"Viscosity errors: {error_array}")

# Plotting the data points
plt.figure(figsize=(8,5))

plt.errorbar(
    temperatures,
    visc_array,
    xerr=temp_error,
    yerr=error_array,
    fmt='o',
    capsize=5
 )

# # Calculating parameters for curve
# popt, pcov = curve_fit(
#     arrhenius_viscosity,
#     T_K,
#     visc_array
# )

# A_fit, Ea_fit = popt

# print(f"A = {A_fit:.3e}")
# print(f"Ea = {Ea_fit/1000:.2f} kJ/mol")

popt, pcov = curve_fit(
    VFT,
    T_K,
    visc_array,
    sigma=error_array,
    absolute_sigma=True,
    p0=[1e-5, 15000]  # initial guesses
)

eta_0_fit, B_fit = popt
print(f"eta_0 = {eta_0_fit} and B = {B_fit}")

eta_0_err, B_err = np.sqrt(np.diag(pcov))
print(f"eta_0_err = {eta_0_err} and B_err = {B_err}")

# Calculating R^2 value
eta_fit = VFT(T_K, *popt)

ss_res = np.sum((visc_array - eta_fit)**2)
ss_tot = np.sum((visc_array - np.mean(visc_array))**2)

r_squared = 1 - ss_res/ss_tot

print(f"R² = {r_squared:.4f}")

# Plotting the curve
plt.plot(
    T_fit - 273.15,
    VFT(T_fit, *popt),
    label=fr"$R^2 = {r_squared:.3f}$"
)

# Changing plot labels
plt.xlabel("Temperature (°C)", fontsize = 16)
plt.ylabel("Viscosity (Pa·s)", fontsize = 16)
plt.title("Viscosity Dependence of Sunflower Oil", fontsize = 16)

plt.grid()
plt.legend(fontsize=12)

plt.savefig("Sunflower_dependency_VFT", dpi = 300)

plt.show()