# -*- coding: utf-8 -*-
"""PLDP_data_analysis_sunflower_oil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nzjj6N_6NpM-SyZb0eIuM3ksqfL-EsWs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.optimize import curve_fit

# ----------------------------------
# Sphere properties and other constants
# ----------------------------------

d = 0.03          # m
dd = 0.001        # m

r = d/2

m = 0.0157        # kg

rho_oil = 920     # kg/m^3

g = 9.81  # m/s^2

R = 8.314  # J/(mol K)

# sphere density
V = (4/3)*np.pi*r**3
rho_s = m/V

print(f"Sphere density = {rho_s:.1f} kg/m^3")


# ----------------------------------
# Read Tracker file
# ----------------------------------

def read_tracker(filename):

    df = pd.read_csv(
        filename,
        skiprows=1
    )

    return df


# ----------------------------------
# Terminal velocity estimate
# ----------------------------------

def terminal_velocity(df, n_points=10):

    vy = pd.to_numeric(
        df["vy"],
        errors="coerce"
    )

    vy = vy.dropna()

    # looks for 10 most negative values, takes the mean and std
    lowest = np.sort(vy)[:n_points]

    v_term = abs(np.mean(lowest))
    v_std = np.std(lowest, ddof=1)

    return v_term, v_std


# ----------------------------------
# Stokes viscosity
# ----------------------------------

def viscosity(v):

    return (
        2*r**2*(rho_s-rho_oil)*g
        /
        (9*v)
    )


# ----------------------------------
# Process one file
# ----------------------------------

def analyze_file(filename):

    df = read_tracker(filename)

    v, dv = terminal_velocity(df)

    eta = viscosity(v)

    deta = eta * dv / v

    return v, dv, eta, deta

# ----------------------------------
# Arrhenius function to fit to data
# ----------------------------------

def arrhenius_viscosity(T, A, Ea):
    return A * np.exp(Ea / (R * T))


def simple_decay(T, A_0, t_0):
  return A_0*no.exp(-T/t_0)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~22/Data f oil 22/f_oil_21,5.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~22/Data f oil 22/f_oil_21,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~22/Data f oil 22/f_oil_second_21,5.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~22/Data f oil 22/f_oil_second_21,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~22/Data f oil 22/f_oil_third_21,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_21,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_second_21,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/22/m_oil_third_21,9.txt"
]

trial_viscosities = [] # This contains all trials of one temp
viscosity_list = [] # This will contain all final viscosities
error_list = [] # This will contain all final errors of viscosity

for file in files:

    v, dv, eta, deta = analyze_file(file)

    print("\n", file)

    print("v =", round(v,3), "m/s")

    print("viscosity =", round(eta,3), "Pa·s")

    print("error =", round(deta,3), "Pa·s")

    trial_viscosities.append(eta)

final_viscosity_22 = np.mean(trial_viscosities)
error_viscosity_22 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_22)
error_list.append(error_viscosity_22)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_26,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_26,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_26,5.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_26,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_27,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_27,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~27/Data f oil 27/f_oil_second_26,4.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_27 = np.mean(trial_viscosities)
error_viscosity_27 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_27)
error_list.append(error_viscosity_27)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_31,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_31,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_31,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_32,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_32,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~32/Data f oil 32/f_oil_35,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/32/m_oil_32,7.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_32 = np.mean(trial_viscosities)
error_viscosity_32 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_32)
error_list.append(error_viscosity_32)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_36,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_36,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/37/m_oil_37,7.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_37 = np.mean(trial_viscosities)
error_viscosity_37 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_37)
error_list.append(error_viscosity_37)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~42/Data f oil 42/f_oil_40,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~42/Data f oil 42/f_oil_40,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~42/Data f oil 42/f_oil_41,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~42/Data f oil 42/f_oil_42,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~42/Data f oil 42/f_oil_second_42,6.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_41,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_42,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_42,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/42/m_oil_second_42,3.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_42 = np.mean(trial_viscosities)
error_viscosity_42 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_42)
error_list.append(error_viscosity_42)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_46,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/47/m_oil_47,8.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_47 = np.mean(trial_viscosities)
error_viscosity_47 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_47)
error_list.append(error_viscosity_47)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_49,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_49,7.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_49,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_50,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_51,7.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /~52/Data f oil 52/f_oil_51,8.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,3.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_52,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/52/m_oil_second_52,4.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_52 = np.mean(trial_viscosities)
error_viscosity_52 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_52)
error_list.append(error_viscosity_52)

# DATA 57 DEGREES LEFT OUT DUE TO LARGE ERROR IN RECORDING

# files = [
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_57,2.txt",
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_57,6.txt",
#     "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/57/m_oil_second_57,6.txt"
# ]

# trial_viscosities = []

# for file in files:

#     v, dv, eta, deta = analyze_file(file)

#     trial_viscosities.append(eta)

# final_viscosity_57 = np.mean(trial_viscosities)
# error_viscosity_57 = np.std(trial_viscosities, ddof = 1)

# print(trial_viscosities)

# viscosity_list.append(final_viscosity_57)
# error_list.append(error_viscosity_57)

files = [
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_61,9.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,0.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,2.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_62,4.txt",
    "/content/drive/MyDrive/Physics Lab: Design Project/Oil friday /Oil 08.06.2026/62/m_oil_second_62,0.txt"
]

trial_viscosities = []

for file in files:

    v, dv, eta, deta = analyze_file(file)

    trial_viscosities.append(eta)

final_viscosity_62 = np.mean(trial_viscosities)
error_viscosity_62 = np.std(trial_viscosities, ddof = 1)
viscosity_list.append(final_viscosity_62)
error_list.append(error_viscosity_62)

temperatures = [22, 27, 32, 37, 42, 47, 52, 66] # degrees Celsius
temp_error = 2

T = np.array(temperatures)
T_K = T + 273.15 # Conversion to Kelvin for curve_fit()
T_fit = np.linspace(min(T_K), max(T_K), 200)

visc_array = np.array(viscosity_list) # For table with final data
error_array = np.array(error_list) # For table with final data
print(f"Viscosity values: {visc_array}")
print(f"Viscosity errors: {error_array}")

# Plotting the data points
plt.errorbar(
    temperatures,
    visc_array,
    xerr=temp_error,
    yerr=error_array,
    fmt='o',
    capsize=5
 )

# Calculating parameters for curve
popt, pcov = curve_fit(
    arrhenius_viscosity,
    T_K,
    visc_array
)

A_fit, Ea_fit = popt

print(f"A = {A_fit:.3e}")
print(f"Ea = {Ea_fit/1000:.2f} kJ/mol")

# Calculating R^2 value
y_fit = arrhenius_viscosity(T_K, *popt)

ss_res = np.sum((visc_array - y_fit)**2)
ss_tot = np.sum((visc_array - np.mean(visc_array))**2)

r_squared = 1 - ss_res/ss_tot

print(f"R² = {r_squared:.5f}")

# Plotting the curve
plt.plot(
    T_fit - 273.15,
    arrhenius_viscosity(T_fit, *popt),
    label=fr"Arrhenius Fit ($R^2 = {r_squared:.3f}$)"
)

# Changing plot labels
plt.xlabel("Temperature (°C)", fontsize = 16)
plt.ylabel("Viscosity (Pa·s)", fontsize = 16)
plt.title("Viscosity Dependence of Sunflower Oil", fontsize = 16)

plt.grid()
plt.legend(fontsize=12)

plt.savefig("Viscosity_Dependence_Sunflower_Oil", dpi = 300)

plt.show()

pop, pco = curve_fit(simple_decay,T_K,visc_array)
A_0_fit = pop[0], t_0_fit = pop[1]
fit = simple_decay(T_K,A_0_fit,t_0_fit)
ss_res_0 = np.sum((visc_array-fit)**2)
#print(f"A = {A_fit:.3e}")
#print(f"Ea = {Ea_fit/1000:.2f} kJ/mol")

r_squared_0 = 1 - ss_res_0/ss_tot

plt.plot(T_fit-273.15,simple_decay(T_fit,A_0_fit,t_0_fit))

# Plotting the data points
plt.errorbar(
    temperatures,
    visc_array,
    xerr=temp_error,
    yerr=error_array,
    fmt='o',
    capsize=5
 )

plt,show()