{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5d4c18c",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "# ==========================\n",
    "# Sphere parameters\n",
    "# ==========================\n",
    "\n",
    "g = 9.81             # m/s^2\n",
    "r = 0.015            # m\n",
    "m = 0.0157           # kg\n",
    "rho_water = 998      # kg/m^3\n",
    "\n",
    "V = (4/3)*np.pi*r**3\n",
    "rho_sphere = m/V\n",
    "\n",
    "print(f\"Sphere density = {rho_sphere:.1f} kg/m^3\")\n",
    "\n",
    "# ==========================\n",
    "# Experimental data\n",
    "# ==========================\n",
    "\n",
    "T_C = np.array([22, 30.64285714, 36.51428571, 39.96666,\n",
    "                45.8, 50.175, 55.825, 60.75, 65.2])\n",
    "\n",
    "T_err = np.array([0.1, 0.454082015, 0.835520938, 0.763762616,\n",
    "                  0.806225775, 0.916125381, 1.837344098, 1.21449578, 1.476482306])\n",
    "\n",
    "v = np.array([0.4964, 0.5187143, 0.5252857, 0.527666,\n",
    "              0.5362, 0.544125, 0.53075, 0.5543333, 0.5548])\n",
    "\n",
    "v_err = np.array([0.018533, 0.0238491, 0.0225697, 0.040089,\n",
    "                  0.025945, 0.038632125, 0.02888075, 0.0387365, 0.0315118])\n",
    "\n",
    "# ==========================\n",
    "# Stokes viscosity\n",
    "# ==========================\n",
    "\n",
    "def viscosity_stokes(v, r, rho_s, rho_f):\n",
    "    return (2 * r**2 * (rho_s - rho_f) * g) / (9 * v)\n",
    "\n",
    "eta = viscosity_stokes(v, r, rho_sphere, rho_water)\n",
    "eta_err = eta * (v_err / v)\n",
    "\n",
    "T_K = T_C + 273.15\n",
    "\n",
    "print(f\"Viscosity:       {eta}\")\n",
    "print(f\"Viscosity error: {eta_err}\")\n",
    "print(f\"Temperature:     {T_C}\")\n",
    "print(f\"T error:         {T_err}\")\n",
    "\n",
    "# ==========================\n",
    "# VFT fit  (3 free parameters)\n",
    "# ==========================\n",
    "\n",
    "def VFT(T, eta_0, B, T_tf):\n",
    "    return eta_0 * np.exp(B / (T - T_tf))\n",
    "\n",
    "popt, pcov = curve_fit(\n",
    "    VFT,\n",
    "    T_K,\n",
    "    eta,\n",
    "    sigma=eta_err,\n",
    "    absolute_sigma=True,\n",
    "    p0=[2.9e-5, 507.88, 149.3],\n",
    "    bounds=(\n",
    "        [0,        0,    0],\n",
    "        [np.inf, np.inf, 273.15]   # T_tf must stay below min data temperature\n",
    "    )\n",
    ")\n",
    "\n",
    "eta_0_fit, B_fit, T_tf_fit = popt\n",
    "eta_0_err, B_err, T_tf_err = np.sqrt(np.diag(pcov))\n",
    "\n",
    "print(f\"\\nVFT fit results:\")\n",
    "print(f\"eta_0 = ({eta_0_fit:.3e} ± {eta_0_err:.3e}) Pa·s\")\n",
    "print(f\"B     = ({B_fit:.2f} ± {B_err:.2f}) K\")\n",
    "print(f\"T_tf  = ({T_tf_fit:.2f} ± {T_tf_err:.2f}) K\")\n",
    "\n",
    "# ==========================\n",
    "# R²\n",
    "# ==========================\n",
    "\n",
    "eta_fit_vals = VFT(T_K, *popt)\n",
    "ss_res = np.sum((eta - eta_fit_vals)**2)\n",
    "ss_tot = np.sum((eta - np.mean(eta))**2)\n",
    "r_squared = 1 - ss_res / ss_tot\n",
    "\n",
    "print(f\"R²    = {r_squared:.4f}\")\n",
    "\n",
    "# ==========================\n",
    "# Plot: viscosity vs temperature\n",
    "# ==========================\n",
    "\n",
    "T_plot = np.linspace(min(T_K), max(T_K), 500)\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "\n",
    "plt.errorbar(T_C, eta, xerr=T_err, yerr=eta_err,\n",
    "             fmt='o', capsize=4, label='Data')\n",
    "\n",
    "plt.plot(T_plot - 273.15, VFT(T_plot, *popt),\n",
    "         color='red', linewidth=2,\n",
    "         label=f\"VFT fit ($R^2 = {r_squared:.4f}$)\")\n",
    "\n",
    "plt.xlabel('Temperature (°C)', fontsize=16)\n",
    "plt.ylabel('Viscosity (Pa·s)', fontsize=16)\n",
    "plt.title('Water Viscosity vs Temperature', fontsize=16)\n",
    "plt.grid()\n",
    "plt.legend(fontsize=12)\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"Viscosity_Dependence_Water.png\", dpi=300)\n",
    "plt.show()\n",
    "\n",
    "# ==========================\n",
    "# Plot: velocity vs temperature\n",
    "# ==========================\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "\n",
    "plt.errorbar(T_C, v, xerr=T_err, yerr=v_err,\n",
    "             fmt='o', capsize=4)\n",
    "\n",
    "plt.xlabel('Temperature (°C)', fontsize=16)\n",
    "plt.ylabel('Terminal velocity (m/s)', fontsize=16)\n",
    "plt.title('Terminal Velocity vs Temperature', fontsize=16)\n",
    "plt.grid()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "\n",
    "\n",
    "# ==========================\n",
    "# Plot: velocity vs temperature with fit\n",
    "# ==========================\n",
    "\n",
    "def u_inf(T, eta_0, B, T_tf):\n",
    "    d = 2 * r                          # diameter\n",
    "    return (d**2 * (rho_sphere - rho_water) * g) / (18 * VFT(T, eta_0, B, T_tf))\n",
    "\n",
    "popt_v, pcov_v = curve_fit(\n",
    "    u_inf,\n",
    "    T_K,\n",
    "    v,\n",
    "    sigma=v_err,\n",
    "    absolute_sigma=True,\n",
    "    p0=[2.9e-5, 507.88, 149.3],\n",
    "    bounds=(\n",
    "        [0,      0,    0],\n",
    "        [np.inf, np.inf, 273.15]\n",
    "    )\n",
    ")\n",
    "\n",
    "eta_fit_v = u_inf(T_plot, *popt_v)\n",
    "\n",
    "v_fit_vals = u_inf(T_K, *popt_v)\n",
    "ss_res_v = np.sum((v - v_fit_vals)**2)\n",
    "ss_tot_v = np.sum((v - np.mean(v))**2)\n",
    "r_squared_v = 1 - ss_res_v / ss_tot_v\n",
    "\n",
    "print(f\"Velocity fit R² = {r_squared_v:.4f}\")\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "\n",
    "plt.errorbar(T_C, v, xerr=T_err, yerr=v_err,\n",
    "             fmt='o', capsize=4, label='Data')\n",
    "\n",
    "plt.plot(T_plot - 273.15, u_inf(T_plot, *popt_v),\n",
    "         color='red', linewidth=2,\n",
    "         label=f\"Stokes/VFT fit ($R^2 = {r_squared_v:.4f}$)\")\n",
    "\n",
    "plt.xlabel('Temperature (°C)', fontsize=16)\n",
    "plt.ylabel('Terminal velocity (m/s)', fontsize=16)\n",
    "plt.title('Terminal Velocity vs Temperature', fontsize=16)\n",
    "plt.grid()\n",
    "plt.legend(fontsize=12)\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"Velocity_Dependence_Water.png\", dpi=300)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
